from typing import Optional
from pydantic import BaseModel, Field

# --- MODELS (Pydantic Schemas) ---
# These define what our data should look like (the "Sign at the Roller Coaster")

class Book(BaseModel):
    id: int
    title: str = Field(..., example="The Great Gatsby")
    author: str = Field(..., example="F. Scott Fitzgerald")
    pages: int = Field(..., gt=0, example=180)
    is_read: bool = False
    is_available: bool = True

    model_config = {
        "from_attributes": True
    }

class BookCreate(BaseModel):
    """Schema for creating a book (ID is generated by the 'server')"""
    title: str
    author: str
    pages: int
    is_read: bool = False

class BookUpdate(BaseModel):
    """Schema for updating a book (all fields optional)"""
    title: Optional[str] = None
    author: Optional[str] = None
    pages: Optional[int] = None
    is_read: Optional[bool] = None
